from typing import Optional, List, Protocol
from uuid import UUID

from ..entities import (
    Automation, Batch, Item,
    Run, BatchExecution, ItemExecution, ItemStateHistory,
    Engine, OrchestrationInstance, RunOrchestration
)
from ..enums import ExecutionStatus


class AutomationRepository(Protocol):
    """Interface for Automation repository."""

    def get(self, id: UUID, include_soft_deleted: bool = False) -> Optional[Automation]: ...
    def get_or_raise(self, id: UUID, include_soft_deleted: bool = False) -> Automation: ...
    def get_by_name(self, name: str, include_soft_deleted: bool = False) -> Optional[Automation]: ...
    def list(self, include_soft_deleted: bool = False, **filters) -> List[Automation]: ...
    def list_active(self, limit: int = 100, offset: int = 0) -> List[Automation]: ...
    def create(self, entity: Automation, user: Optional[str] = None) -> Automation: ...
    def update(self, id: UUID, entity: Automation, user: Optional[str] = None) -> Automation: ...
    def delete(self, id: UUID, soft: bool = False, user: Optional[str] = None, expected_version: Optional[int] = None) -> bool: ...
    def exists(self, id: UUID, include_soft_deleted: bool = False) -> bool: ...
    def count(self, include_soft_deleted: bool = False, **filters) -> int: ...


class RunRepository(Protocol):
    """Interface for Run repository."""

    def get(self, id: UUID, include_soft_deleted: bool = False) -> Optional[Run]: ...
    def get_by_correlation_id(self, correlation_id: str, include_soft_deleted: bool = False) -> Optional[Run]: ...
    def list_by_automation(self, automation_id: UUID, limit: int = 100, offset: int = 0, status: Optional[ExecutionStatus] = None, include_soft_deleted: bool = False) -> List[Run]: ...
    def list_by_status(self, status: ExecutionStatus, limit: int = 100, offset: int = 0, include_soft_deleted: bool = False) -> List[Run]: ...
    def find_running(self, automation_id: Optional[UUID] = None, include_soft_deleted: bool = False) -> List[Run]: ...
    def create(self, entity: Run, user: Optional[str] = None) -> Run: ...
    def update(self, id: UUID, entity: Run, user: Optional[str] = None) -> Run: ...
    def delete(self, id: UUID, soft: bool = False, user: Optional[str] = None, expected_version: Optional[int] = None) -> bool: ...
    def exists(self, id: UUID, include_soft_deleted: bool = False) -> bool: ...
    def count(self, include_soft_deleted: bool = False, **filters) -> int: ...


class ItemExecutionRepository(Protocol):
    """Interface for ItemExecution repository."""

    def get(self, id: UUID, include_soft_deleted: bool = False) -> Optional[ItemExecution]: ...
    def get_by_run_and_item(self, run_id: UUID, item_id: UUID, include_soft_deleted: bool = False) -> Optional[ItemExecution]: ...
    def list_by_batch_execution(self, batch_execution_id: UUID, include_soft_deleted: bool = False, limit: int = 100, offset: int = 0) -> List[ItemExecution]: ...
    def list_pending_by_run(self, run_id: UUID, include_soft_deleted: bool = False, limit: int = 100, offset: int = 0) -> List[ItemExecution]: ...
    def list_failed_by_run(self, run_id: UUID, include_soft_deleted: bool = False, limit: int = 100, offset: int = 0) -> List[ItemExecution]: ...
    def count_by_status(self, run_id: UUID, status: ExecutionStatus, include_soft_deleted: bool = False) -> int: ...
    def create(self, entity: ItemExecution, user: Optional[str] = None) -> ItemExecution: ...
    def update(self, id: UUID, entity: ItemExecution, user: Optional[str] = None) -> ItemExecution: ...
    def delete(self, id: UUID, soft: bool = False, user: Optional[str] = None, expected_version: Optional[int] = None) -> bool: ...
    def exists(self, id: UUID, include_soft_deleted: bool = False) -> bool: ...
    def count(self, include_soft_deleted: bool = False, **filters) -> int: ...


class ItemStateHistoryRepository(Protocol):
    """Interface for ItemStateHistory repository."""

    def get(self, id: UUID, include_soft_deleted: bool = False) -> Optional[ItemStateHistory]: ...
    def list_by_item_execution(self, item_execution_id: UUID, limit: int = 100, offset: int = 0, include_soft_deleted: bool = False) -> List[ItemStateHistory]: ...
    def get_latest_by_item_execution(self, item_execution_id: UUID, include_soft_deleted: bool = False) -> Optional[ItemStateHistory]: ...
    def create(self, entity: ItemStateHistory, user: Optional[str] = None) -> ItemStateHistory: ...
    def delete(self, id: UUID, soft: bool = False, user: Optional[str] = None, expected_version: Optional[int] = None) -> bool: ...
    def exists(self, id: UUID, include_soft_deleted: bool = False) -> bool: ...
    def count(self, include_soft_deleted: bool = False, **filters) -> int: ...


class BatchRepository(Protocol):
    """Interface for Batch repository."""

    def get(self, id: UUID, include_soft_deleted: bool = False) -> Optional[Batch]: ...
    def get_by_automation_and_name(self, automation_id: UUID, name: str, include_soft_deleted: bool = False) -> Optional[Batch]: ...
    def list_by_automation(self, automation_id: UUID, include_soft_deleted: bool = False, limit: int = 100, offset: int = 0) -> List[Batch]: ...
    def create(self, entity: Batch, user: Optional[str] = None) -> Batch: ...
    def update(self, id: UUID, entity: Batch, user: Optional[str] = None) -> Batch: ...
    def delete(self, id: UUID, soft: bool = False, user: Optional[str] = None, expected_version: Optional[int] = None) -> bool: ...
    def exists(self, id: UUID, include_soft_deleted: bool = False) -> bool: ...
    def count(self, include_soft_deleted: bool = False, **filters) -> int: ...


class ItemRepository(Protocol):
    """Interface for Item repository."""

    def get(self, id: UUID, include_soft_deleted: bool = False) -> Optional[Item]: ...
    def get_by_batch_and_sequence(self, batch_id: UUID, sequence_number: int, include_soft_deleted: bool = False) -> Optional[Item]: ...
    def list_by_batch(self, batch_id: UUID, include_soft_deleted: bool = False, limit: int = 100, offset: int = 0) -> List[Item]: ...
    def create(self, entity: Item, user: Optional[str] = None) -> Item: ...
    def update(self, id: UUID, entity: Item, user: Optional[str] = None) -> Item: ...
    def delete(self, id: UUID, soft: bool = False, user: Optional[str] = None, expected_version: Optional[int] = None) -> bool: ...
    def exists(self, id: UUID, include_soft_deleted: bool = False) -> bool: ...
    def count(self, include_soft_deleted: bool = False, **filters) -> int: ...


class BatchExecutionRepository(Protocol):
    """Interface for BatchExecution repository."""

    def get(self, id: UUID, include_soft_deleted: bool = False) -> Optional[BatchExecution]: ...
    def get_by_run_and_batch(self, run_id: UUID, batch_id: UUID, include_soft_deleted: bool = False) -> Optional[BatchExecution]: ...
    def list_by_run(self, run_id: UUID, include_soft_deleted: bool = False, limit: int = 100, offset: int = 0) -> List[BatchExecution]: ...
    def list_by_batch(self, batch_id: UUID, include_soft_deleted: bool = False, limit: int = 100, offset: int = 0) -> List[BatchExecution]: ...
    def create(self, entity: BatchExecution, user: Optional[str] = None) -> BatchExecution: ...
    def update(self, id: UUID, entity: BatchExecution, user: Optional[str] = None) -> BatchExecution: ...
    def delete(self, id: UUID, soft: bool = False, user: Optional[str] = None, expected_version: Optional[int] = None) -> bool: ...
    def exists(self, id: UUID, include_soft_deleted: bool = False) -> bool: ...
    def count(self, include_soft_deleted: bool = False, **filters) -> int: ...


class EngineRepository(Protocol):
    """Interface for Engine repository."""

    def get(self, id: UUID, include_soft_deleted: bool = False) -> Optional[Engine]: ...
    def get_by_name(self, name: str, include_soft_deleted: bool = False) -> Optional[Engine]: ...
    def list_by_type(self, engine_type: str, include_soft_deleted: bool = False, limit: int = 100, offset: int = 0) -> List[Engine]: ...
    def list(self, include_soft_deleted: bool = False, **filters) -> List[Engine]: ...
    def create(self, entity: Engine, user: Optional[str] = None) -> Engine: ...
    def update(self, id: UUID, entity: Engine, user: Optional[str] = None) -> Engine: ...
    def delete(self, id: UUID, soft: bool = False, user: Optional[str] = None, expected_version: Optional[int] = None) -> bool: ...
    def exists(self, id: UUID, include_soft_deleted: bool = False) -> bool: ...
    def count(self, include_soft_deleted: bool = False, **filters) -> int: ...


class OrchestrationInstanceRepository(Protocol):
    """Interface for OrchestrationInstance repository."""

    def get(self, id: UUID, include_soft_deleted: bool = False) -> Optional[OrchestrationInstance]: ...
    def get_by_engine_and_external(self, engine_id: UUID, external_id: str, include_soft_deleted: bool = False) -> Optional[OrchestrationInstance]: ...
    def list_by_engine(self, engine_id: UUID, include_soft_deleted: bool = False, limit: int = 100, offset: int = 0) -> List[OrchestrationInstance]: ...
    def list_by_status(self, status: ExecutionStatus, include_soft_deleted: bool = False, limit: int = 100, offset: int = 0) -> List[OrchestrationInstance]: ...
    def list_running(self, include_soft_deleted: bool = False, limit: int = 100, offset: int = 0) -> List[OrchestrationInstance]: ...
    def create(self, entity: OrchestrationInstance, user: Optional[str] = None) -> OrchestrationInstance: ...
    def update(self, id: UUID, entity: OrchestrationInstance, user: Optional[str] = None) -> OrchestrationInstance: ...
    def delete(self, id: UUID, soft: bool = False, user: Optional[str] = None, expected_version: Optional[int] = None) -> bool: ...
    def exists(self, id: UUID, include_soft_deleted: bool = False) -> bool: ...
    def count(self, include_soft_deleted: bool = False, **filters) -> int: ...


class RunOrchestrationRepository(Protocol):
    """Interface for RunOrchestration repository."""

    def get(self, id: UUID, include_soft_deleted: bool = False) -> Optional[RunOrchestration]: ...
    def get_by_run_and_instance(self, run_id: UUID, instance_id: UUID, include_soft_deleted: bool = False) -> Optional[RunOrchestration]: ...
    def list_by_run(self, run_id: UUID, include_soft_deleted: bool = False, limit: int = 100, offset: int = 0) -> List[RunOrchestration]: ...
    def list_by_instance(self, instance_id: UUID, include_soft_deleted: bool = False, limit: int = 100, offset: int = 0) -> List[RunOrchestration]: ...
    def create(self, entity: RunOrchestration, user: Optional[str] = None) -> RunOrchestration: ...
    def update(self, id: UUID, entity: RunOrchestration, user: Optional[str] = None) -> RunOrchestration: ...
    def delete(self, id: UUID, soft: bool = False, user: Optional[str] = None, expected_version: Optional[int] = None) -> bool: ...
    def exists(self, id: UUID, include_soft_deleted: bool = False) -> bool: ...
    def count(self, include_soft_deleted: bool = False, **filters) -> int: ...
